### PR TITLE
1.3.1 sdk upgrade

### PR DESCRIPTION
**Pull request by mrbonezy**

### CODE REVIEW

**Review by wlofman021 — COMMENTED** [review]
0b5d11ce60c014c4204d42c64ec0c2617bedc86b

**Review by wlofman021 — COMMENTED** [review]
fix

**Review by 10208612 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by Cabdulaahi6649 — COMMENTED** [review]
H

**Review by MrG9090 — APPROVED** [review]

**Review by Milad335t — APPROVED** [review]

**Review by Milad335t — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by Frenky9871 — APPROVED** [review]

**Review by Frenky9871 — APPROVED** [review]

**Comment by cumcum8197** [comment]
78273f4399c8732e889927606666b603ffdfaee9

**Comment by cumcum8197** [comment]
78273f4399c8732e889927606666b603ffdfaee9

**Comment by cumcum8197** [comment]
78273f4399c8732e889927606666b603ffdfaee9

**Comment by cumcum8197** [comment]
b4eedc89999d21c3030c5b11811a5b82b5a099b8

**Comment by cumcum8197** [comment]
de2cc778933c920130a44afce5bb1b617bff00d7

**Comment by cumcum8197** [comment]
0b5d11ce60c014c4204d42c64ec0c2617bedc86b

**Comment by cumcum8197** [comment]
78273f4399c8732e889927606666b603ffdfaee9

**Comment by cumcum8197** [comment]
b4eedc89999d21c3030c5b11811a5b82b5a099b8

**Comment by cumcum8197** [comment]
b4eedc89999d21c3030c5b11811a5b82b5a099b8

**Comment by cumcum8197** [comment]
b4eedc89999d21c3030c5b11811a5b82b5a099b8

**Review by Kubanyyy — COMMENTED** [review]
We good

**Review by wkhr9d9hyd-sys — COMMENTED** [review]
M

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Pull request merged**
